project:
  type: website

website:
  title: "T5_BC2_2023_ex1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

