---
title: "analysis"
---

```{r}
#| output: false
library(babynames)
library(knitr)
library(dplyr)
library(ggplot2)
```

```{r}
head(babynames) |> kable()
```


```r
# Code not evaluated when rendering
# r without curly brackets
head(babynames) |> kable()
```

```{r}
#| code-fold: true
get_most_frequent <- function(babynames, select_sex, from = 1950) {
  most_freq <- babynames |>
    filter(sex == select_sex, year > from) |>
    group_by(name) |>
    summarise(average = mean(prop)) |>
    arrange(desc(average))
    
  return(list(
    babynames = babynames,
    most_frequent = most_freq,
    sex = select_sex,
    from = from))
}

plot_top <- function(x, top = 10) {
  topx <- x$most_frequent$name[1:top]
  
  p <- x$babynames |>
    filter(name %in% topx, sex == x$sex, year > x$from) |>
    ggplot(aes(x = year, y = prop, color = name)) +
    geom_line() +
    scale_color_brewer(palette = "Paired") +
    theme_classic()
  
  return(p)
}
```

```{r}
#| label: "fig-babygirl-names"
#| fig-cap: "babygirl names"
#| fig-align: "left"
get_most_frequent(babynames, select_sex = "F") |>
  plot_top()
```

```{r}
#| label: "fig-babyboy-names"
#| fig-cap: "babyboy names"
#| fig-align: "left"
get_most_frequent(babynames, select_sex = "M") |>
  plot_top()
```

In @fig-babygirl-names we see the 10 most popular names for baby girls, and in @fig-babyboy-names we see the 10 most popular names for baby boys since 1950.

```{r}

```
